//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.GuestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:guest", ConfigurationName="GuestService.guestPort")]
    public interface guestPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#getGuest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.getGuestResponse getGuest(WebApplication1.GuestService.getGuestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#sendMessageDiy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.sendMessageDiyResponse sendMessageDiy(WebApplication1.GuestService.sendMessageDiyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#sendMessageAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.sendMessageAllResponse sendMessageAll(WebApplication1.GuestService.sendMessageAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#sendMessagePage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.sendMessagePageResponse sendMessagePage(WebApplication1.GuestService.sendMessagePageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#tutorStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.tutorStatisticsResponse tutorStatistics(WebApplication1.GuestService.tutorStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#tutorResultStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.tutorResultStatisticsResponse tutorResultStatistics(WebApplication1.GuestService.tutorResultStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#searchApp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.searchAppResponse searchApp(WebApplication1.GuestService.searchAppRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#addAppFavorite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.addAppFavoriteResponse addAppFavorite(WebApplication1.GuestService.addAppFavoriteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#removeAppFavorite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.removeAppFavoriteResponse removeAppFavorite(WebApplication1.GuestService.removeAppFavoriteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#listAppFavorite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.listAppFavoriteResponse listAppFavorite(WebApplication1.GuestService.listAppFavoriteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#getServiceCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.getServiceCategoryResponse getServiceCategory(WebApplication1.GuestService.getServiceCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#getService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.getServiceResponse getService(WebApplication1.GuestService.getServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#sendMessageServiceDiy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.sendMessageServiceDiyResponse sendMessageServiceDiy(WebApplication1.GuestService.sendMessageServiceDiyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#sendMessageServicePage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.sendMessageServicePageResponse sendMessageServicePage(WebApplication1.GuestService.sendMessageServicePageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#addServiceFavorite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.addServiceFavoriteResponse addServiceFavorite(WebApplication1.GuestService.addServiceFavoriteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#removeServiceFavorite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.removeServiceFavoriteResponse removeServiceFavorite(WebApplication1.GuestService.removeServiceFavoriteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#searchService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.searchServiceResponse searchService(WebApplication1.GuestService.searchServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:guest#guest#serviceStatistics", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.GuestService.serviceStatisticsResponse serviceStatistics(WebApplication1.GuestService.serviceStatisticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGuest", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class getGuestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string page;
        
        public getGuestRequest() {
        }
        
        public getGuestRequest(string uid, string page) {
            this.uid = uid;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGuestResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class getGuestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getGuest;
        
        public getGuestResponse() {
        }
        
        public getGuestResponse(string getGuest) {
            this.getGuest = getGuest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageDiy", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageDiyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string uid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string tname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string r2_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string cellphone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string aid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string time;
        
        public sendMessageDiyRequest() {
        }
        
        public sendMessageDiyRequest(string uid, string tname, string r2_id, string cellphone, string aid, string title, string message, string time) {
            this.uid = uid;
            this.tname = tname;
            this.r2_id = r2_id;
            this.cellphone = cellphone;
            this.aid = aid;
            this.title = title;
            this.message = message;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageDiyResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageDiyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendMessageDiy;
        
        public sendMessageDiyResponse() {
        }
        
        public sendMessageDiyResponse(string sendMessageDiy) {
            this.sendMessageDiy = sendMessageDiy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageAll", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string tname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string aid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string r2_id;
        
        public sendMessageAllRequest() {
        }
        
        public sendMessageAllRequest(string tid, string tname, string aid, string r2_id) {
            this.tid = tid;
            this.tname = tname;
            this.aid = aid;
            this.r2_id = r2_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageAllResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendMessageAll;
        
        public sendMessageAllResponse() {
        }
        
        public sendMessageAllResponse(string sendMessageAll) {
            this.sendMessageAll = sendMessageAll;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagePage", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessagePageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string tname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string r2_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string aid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cellphone;
        
        public sendMessagePageRequest() {
        }
        
        public sendMessagePageRequest(string tid, string tname, string r2_id, string aid, string cellphone) {
            this.tid = tid;
            this.tname = tname;
            this.r2_id = r2_id;
            this.aid = aid;
            this.cellphone = cellphone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessagePageResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessagePageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendMessagePage;
        
        public sendMessagePageResponse() {
        }
        
        public sendMessagePageResponse(string sendMessagePage) {
            this.sendMessagePage = sendMessagePage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tutorStatistics", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class tutorStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string time;
        
        public tutorStatisticsRequest() {
        }
        
        public tutorStatisticsRequest(string tid, string time) {
            this.tid = tid;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tutorStatisticsResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class tutorStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tutorStatistics;
        
        public tutorStatisticsResponse() {
        }
        
        public tutorStatisticsResponse(string tutorStatistics) {
            this.tutorStatistics = tutorStatistics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tutorResultStatistics", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class tutorResultStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string r2_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string time;
        
        public tutorResultStatisticsRequest() {
        }
        
        public tutorResultStatisticsRequest(string tid, string r2_id, string time) {
            this.tid = tid;
            this.r2_id = r2_id;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tutorResultStatisticsResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class tutorResultStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tutorResultStatistics;
        
        public tutorResultStatisticsResponse() {
        }
        
        public tutorResultStatisticsResponse(string tutorResultStatistics) {
            this.tutorResultStatistics = tutorResultStatistics;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchApp", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class searchAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string cid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string page;
        
        public searchAppRequest() {
        }
        
        public searchAppRequest(string key, string cid, string page) {
            this.key = key;
            this.cid = cid;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchAppResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class searchAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string searchApp;
        
        public searchAppResponse() {
        }
        
        public searchAppResponse(string searchApp) {
            this.searchApp = searchApp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAppFavorite", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class addAppFavoriteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string aid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string tid;
        
        public addAppFavoriteRequest() {
        }
        
        public addAppFavoriteRequest(string aid, string tid) {
            this.aid = aid;
            this.tid = tid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAppFavoriteResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class addAppFavoriteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string addAppFavorite;
        
        public addAppFavoriteResponse() {
        }
        
        public addAppFavoriteResponse(string addAppFavorite) {
            this.addAppFavorite = addAppFavorite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAppFavorite", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class removeAppFavoriteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string aid;
        
        public removeAppFavoriteRequest() {
        }
        
        public removeAppFavoriteRequest(string tid, string aid) {
            this.tid = tid;
            this.aid = aid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAppFavoriteResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class removeAppFavoriteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string removeAppFavorite;
        
        public removeAppFavoriteResponse() {
        }
        
        public removeAppFavoriteResponse(string removeAppFavorite) {
            this.removeAppFavorite = removeAppFavorite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAppFavorite", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class listAppFavoriteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        public listAppFavoriteRequest() {
        }
        
        public listAppFavoriteRequest(string tid) {
            this.tid = tid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAppFavoriteResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class listAppFavoriteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string listAppFavorite;
        
        public listAppFavoriteResponse() {
        }
        
        public listAppFavoriteResponse(string listAppFavorite) {
            this.listAppFavorite = listAppFavorite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceCategory", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class getServiceCategoryRequest {
        
        public getServiceCategoryRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceCategoryResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class getServiceCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getServiceCategory;
        
        public getServiceCategoryResponse() {
        }
        
        public getServiceCategoryResponse(string getServiceCategory) {
            this.getServiceCategory = getServiceCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getService", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class getServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cid;
        
        public getServiceRequest() {
        }
        
        public getServiceRequest(string cid) {
            this.cid = cid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class getServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getService;
        
        public getServiceResponse() {
        }
        
        public getServiceResponse(string getService) {
            this.getService = getService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageServiceDiy", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageServiceDiyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cellphone;
        
        public sendMessageServiceDiyRequest() {
        }
        
        public sendMessageServiceDiyRequest(string tid, string sid, string cellphone) {
            this.tid = tid;
            this.sid = sid;
            this.cellphone = cellphone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageServiceDiyResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageServiceDiyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendMessageServiceDiy;
        
        public sendMessageServiceDiyResponse() {
        }
        
        public sendMessageServiceDiyResponse(string sendMessageServiceDiy) {
            this.sendMessageServiceDiy = sendMessageServiceDiy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageServicePage", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageServicePageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string cellphone;
        
        public sendMessageServicePageRequest() {
        }
        
        public sendMessageServicePageRequest(string tid, string sid, string cellphone) {
            this.tid = tid;
            this.sid = sid;
            this.cellphone = cellphone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageServicePageResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class sendMessageServicePageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendMessageServicePage;
        
        public sendMessageServicePageResponse() {
        }
        
        public sendMessageServicePageResponse(string sendMessageServicePage) {
            this.sendMessageServicePage = sendMessageServicePage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addServiceFavorite", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class addServiceFavoriteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string tid;
        
        public addServiceFavoriteRequest() {
        }
        
        public addServiceFavoriteRequest(string id, string tid) {
            this.id = id;
            this.tid = tid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addServiceFavoriteResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class addServiceFavoriteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string addServiceFavorite;
        
        public addServiceFavoriteResponse() {
        }
        
        public addServiceFavoriteResponse(string addServiceFavorite) {
            this.addServiceFavorite = addServiceFavorite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeServiceFavorite", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class removeServiceFavoriteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string id;
        
        public removeServiceFavoriteRequest() {
        }
        
        public removeServiceFavoriteRequest(string tid, string id) {
            this.tid = tid;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeServiceFavoriteResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class removeServiceFavoriteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string removeServiceFavorite;
        
        public removeServiceFavoriteResponse() {
        }
        
        public removeServiceFavoriteResponse(string removeServiceFavorite) {
            this.removeServiceFavorite = removeServiceFavorite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchService", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class searchServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string category;
        
        public searchServiceRequest() {
        }
        
        public searchServiceRequest(string key, string category) {
            this.key = key;
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchServiceResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class searchServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string searchService;
        
        public searchServiceResponse() {
        }
        
        public searchServiceResponse(string searchService) {
            this.searchService = searchService;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serviceStatistics", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class serviceStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string tid;
        
        public serviceStatisticsRequest() {
        }
        
        public serviceStatisticsRequest(string tid) {
            this.tid = tid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serviceStatisticsResponse", WrapperNamespace="urn:guest", IsWrapped=true)]
    public partial class serviceStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string serviceStatistics;
        
        public serviceStatisticsResponse() {
        }
        
        public serviceStatisticsResponse(string serviceStatistics) {
            this.serviceStatistics = serviceStatistics;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface guestPortChannel : WebApplication1.GuestService.guestPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class guestPortClient : System.ServiceModel.ClientBase<WebApplication1.GuestService.guestPort>, WebApplication1.GuestService.guestPort {
        
        public guestPortClient() {
        }
        
        public guestPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public guestPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public guestPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public guestPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.GuestService.getGuestResponse getGuest(WebApplication1.GuestService.getGuestRequest request) {
            return base.Channel.getGuest(request);
        }
        
        public WebApplication1.GuestService.sendMessageDiyResponse sendMessageDiy(WebApplication1.GuestService.sendMessageDiyRequest request) {
            return base.Channel.sendMessageDiy(request);
        }
        
        public WebApplication1.GuestService.sendMessageAllResponse sendMessageAll(WebApplication1.GuestService.sendMessageAllRequest request) {
            return base.Channel.sendMessageAll(request);
        }
        
        public WebApplication1.GuestService.sendMessagePageResponse sendMessagePage(WebApplication1.GuestService.sendMessagePageRequest request) {
            return base.Channel.sendMessagePage(request);
        }
        
        public WebApplication1.GuestService.tutorStatisticsResponse tutorStatistics(WebApplication1.GuestService.tutorStatisticsRequest request) {
            return base.Channel.tutorStatistics(request);
        }
        
        public WebApplication1.GuestService.tutorResultStatisticsResponse tutorResultStatistics(WebApplication1.GuestService.tutorResultStatisticsRequest request) {
            return base.Channel.tutorResultStatistics(request);
        }
        
        public WebApplication1.GuestService.searchAppResponse searchApp(WebApplication1.GuestService.searchAppRequest request) {
            return base.Channel.searchApp(request);
        }
        
        public WebApplication1.GuestService.addAppFavoriteResponse addAppFavorite(WebApplication1.GuestService.addAppFavoriteRequest request) {
            return base.Channel.addAppFavorite(request);
        }
        
        public WebApplication1.GuestService.removeAppFavoriteResponse removeAppFavorite(WebApplication1.GuestService.removeAppFavoriteRequest request) {
            return base.Channel.removeAppFavorite(request);
        }
        
        public WebApplication1.GuestService.listAppFavoriteResponse listAppFavorite(WebApplication1.GuestService.listAppFavoriteRequest request) {
            return base.Channel.listAppFavorite(request);
        }
        
        public WebApplication1.GuestService.getServiceCategoryResponse getServiceCategory(WebApplication1.GuestService.getServiceCategoryRequest request) {
            return base.Channel.getServiceCategory(request);
        }
        
        public WebApplication1.GuestService.getServiceResponse getService(WebApplication1.GuestService.getServiceRequest request) {
            return base.Channel.getService(request);
        }
        
        public WebApplication1.GuestService.sendMessageServiceDiyResponse sendMessageServiceDiy(WebApplication1.GuestService.sendMessageServiceDiyRequest request) {
            return base.Channel.sendMessageServiceDiy(request);
        }
        
        public WebApplication1.GuestService.sendMessageServicePageResponse sendMessageServicePage(WebApplication1.GuestService.sendMessageServicePageRequest request) {
            return base.Channel.sendMessageServicePage(request);
        }
        
        public WebApplication1.GuestService.addServiceFavoriteResponse addServiceFavorite(WebApplication1.GuestService.addServiceFavoriteRequest request) {
            return base.Channel.addServiceFavorite(request);
        }
        
        public WebApplication1.GuestService.removeServiceFavoriteResponse removeServiceFavorite(WebApplication1.GuestService.removeServiceFavoriteRequest request) {
            return base.Channel.removeServiceFavorite(request);
        }
        
        public WebApplication1.GuestService.searchServiceResponse searchService(WebApplication1.GuestService.searchServiceRequest request) {
            return base.Channel.searchService(request);
        }
        
        public WebApplication1.GuestService.serviceStatisticsResponse serviceStatistics(WebApplication1.GuestService.serviceStatisticsRequest request) {
            return base.Channel.serviceStatistics(request);
        }
    }
}
