//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.AppService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:app", ConfigurationName="AppService.appPort")]
    public interface appPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:app#app#getAppCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.AppService.getAppCategoryResponse getAppCategory(WebApplication1.AppService.getAppCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:app#app#getApp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebApplication1.AppService.getAppResponse getApp(WebApplication1.AppService.getAppRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppCategory", WrapperNamespace="urn:app", IsWrapped=true)]
    public partial class getAppCategoryRequest {
        
        public getAppCategoryRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppCategoryResponse", WrapperNamespace="urn:app", IsWrapped=true)]
    public partial class getAppCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getAppCategory;
        
        public getAppCategoryResponse() {
        }
        
        public getAppCategoryResponse(string getAppCategory) {
            this.getAppCategory = getAppCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApp", WrapperNamespace="urn:app", IsWrapped=true)]
    public partial class getAppRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string category;
        
        public getAppRequest() {
        }
        
        public getAppRequest(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAppResponse", WrapperNamespace="urn:app", IsWrapped=true)]
    public partial class getAppResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getApp;
        
        public getAppResponse() {
        }
        
        public getAppResponse(string getApp) {
            this.getApp = getApp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface appPortChannel : WebApplication1.AppService.appPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class appPortClient : System.ServiceModel.ClientBase<WebApplication1.AppService.appPort>, WebApplication1.AppService.appPort {
        
        public appPortClient() {
        }
        
        public appPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public appPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public appPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public appPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.AppService.getAppCategoryResponse getAppCategory(WebApplication1.AppService.getAppCategoryRequest request) {
            return base.Channel.getAppCategory(request);
        }
        
        public WebApplication1.AppService.getAppResponse getApp(WebApplication1.AppService.getAppRequest request) {
            return base.Channel.getApp(request);
        }
    }
}
